name: TorchProfiling CI

on:
  push:
    branches: [ "dev0" ]
  pull_request:
    branches: [ "dev0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.18' # 选择所需的 Python 版本

    - name: Install dependencies
      run: |
        sudo apt-get update || true
        sudo apt-get install -y cmake || true

    - name: build and install
      run: |
        pip install -r requirements.txt
        bash script/build.sh

    - name: run tests
      run: |
        pytest 
