name: TorchProfiling CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.18' # 选择所需的 Python 版本

    - name: build and install
      run: |
        bash script/build.sh
        pip install -r requirements.txt

    - name: run tests
      run: |
        pytest 
